import 'controller/subscribe_popup_controller.dart';import 'package:flutter/material.dart';import 'package:raj_singh_s_application3/core/app_export.dart';import 'package:raj_singh_s_application3/widgets/custom_button.dart';import 'package:raj_singh_s_application3/widgets/custom_checkbox.dart';
// ignore_for_file: must_be_immutable
class SubscribePopupDialog extends StatelessWidget {SubscribePopupDialog(this.controller);

SubscribePopupController controller;

@override Widget build(BuildContext context) { return Container(width: getHorizontalSize(325), padding: getPadding(left: 31, top: 34, right: 31, bottom: 34), decoration: AppDecoration.fillBluegray800.copyWith(borderRadius: BorderRadiusStyle.roundedBorder30), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgIllustration, height: getVerticalSize(58), width: getHorizontalSize(78)), Container(width: getHorizontalSize(213), margin: getMargin(left: 25, top: 20, right: 25), child: Text("msg_be_a_premium_us".tr, maxLines: null, textAlign: TextAlign.center, style: AppStyle.txtPoppinsMedium18WhiteA700ab)), Container(margin: getMargin(left: 19, top: 31, right: 19), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Obx(() => CustomCheckbox(text: "lbl_ad_free".tr, value: controller.isCheckbox.value, fontStyle: CheckboxFontStyle.PoppinsRegular12WhiteA700a2_1, onChange: (value) {controller.isCheckbox.value = value;})), Obx(() => CustomCheckbox(text: "msg_get_access_to_a".tr, value: controller.isCheckbox1.value, margin: getMargin(top: 15, right: 44), fontStyle: CheckboxFontStyle.PoppinsRegular12WhiteA700a2_1, onChange: (value) {controller.isCheckbox1.value = value;})), Obx(() => CustomCheckbox(text: "msg_cancel_anytime".tr, value: controller.isCheckbox2.value, margin: getMargin(top: 15), fontStyle: CheckboxFontStyle.PoppinsRegular12WhiteA700a2_1, onChange: (value) {controller.isCheckbox2.value = value;}))])), CustomButton(height: getVerticalSize(50), text: "lbl_subscribe".tr, margin: getMargin(top: 35, bottom: 2), onTap: () {onTapSubscribe();})])); } 
onTapSubscribe() { Get.toNamed(AppRoutes.choosePlanScreen, ); } 
 }
